board/urls.py
from django.conf.urls import url

import board.views as views

urlpatterns = [
    url(r'^(?P<subject_id>[0-9]+)/list/$', views.list, name='list'),
]

paneity/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from auth.views import logout

urlpatterns = [
    # This is the logout url
    url(r'^logout/', logout, name='logout'), 
    # This redirects to the urlpatterns in spirit.urls
    # This makes the spirit forum our homepage
    url(r'^', include('spirit.urls')),
    # This page allows admins to create new users, new courses,
    # new subjects, etc
    url(r'^admin/', admin.site.urls),
    # This redirects to tutoring urls
    url(r'^tutoring/', include('tutor.urls', namespace='tutor')),
    # This redirects to django private chat urls, and this doesn't
    # interfere with the first url()
    # because django looks at them in order from first to last
    url(r'^', include('django_private_chat.urls')),
]

tutor/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # courses will be listed here
    url(r'^$', views.index, name='index'),
    # ex: tutoring/1/tutors/  --------- Page listing tutors and
    # office hours for a given course
    url(r'^(?P<course_id>[0-9]+)/tutors/$', views.tutors, name='tutors'),
    # ex: tutoring/inbox/  --------- This page displays the most recent messages from
    # each person you've talked to
    url(r'^inbox/$', views.inbox, name='inbox'),
    # ex: tutoring/about/  --------- Page detailing who made this webapp and
    # through which program at Reed
    url(r'^about/$', views.about, name='about'),
]

tutor/models.py
from django.db import models
from django.contrib.auth.models import User
from spirit.category.models import Category


class Student(models.Model):
    """
    Profile model for additional info about students
    Right now it just stores whether or not a user is a tutor
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tutor = models.BooleanField(default=False)
    tutoring_classes = models.ManyToManyField(
        'Course',
        blank=True,
        related_name="tutors",
        help_text="The courses that this student can tutor in.")
    enrolled_classes = models.ManyToManyField(
        'Course',
        blank=True,
        related_name="students",
        help_text="The courses that this student is currently enrolled in.")


class Subject(models.Model):
    """
    Subject that course can be taught in (i.e. Math, Humanities)
    """
    abbreviation = models.CharField(
        max_length=4,
        help_text="3-4 letter abbreviation (i.e. HUM)")
    name = models.CharField(
        max_length=50,
        help_text="Full name of the subject (i.e. Humanities)")
    # below we are creating a one-to-one relationship between Subjects and
    # Categories, so that the forum is structured
    # around Reed's departments, not arbitrary categories.
    category = models.OneToOneField(Category, on_delete=models.CASCADE,
                                    null=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        # Validate abbreviation and name
        for field_name in ['abbreviation', 'name']:
            val = getattr(self, field_name, False)
            if field_name == 'abbreviation':
                setattr(self, 'abbreviation', val.upper())
            elif field_name == 'name':
                setattr(self, 'name', val.capitalize())

        # Set up category for subject
        cat = Category.objects.create(title=self.name)
        cat.save()
        self.category = cat

        super(Subject, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Course(models.Model):
    """
    model for a single course that people can tutor in
    """
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,)
    number = models.IntegerField()
    title = models.CharField(
        max_length=100,
        help_text="(i.e. Ancient Mediterranean, or Intro to Economic Analysis)")
    office_hours = models.TextField(
        help_text="(i.e. Eliot 314 M 15:00-17:00, WTh 11:00-11:30)",
        blank=True)
    drop_in_hrs = models.TextField(help_text
    ="(i.e. Lib 389 MTWThF 19:00-21:00)", blank=True)

    def __str__(self):
        return "{} {}".format(self.subject.abbreviation, self.number)

tutor/views.py
import httplib2
import re
import os
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from base64 import urlsafe_b64encode
from apiclient import discovery
from oauth2client import client

import tutor.models as models


def index(request):
    return render(
        request,
        'tutor/index.html',
        {"Courses": list(models.Course.objects.all())})


def tutors(request, course_id):
    """
    View for the tutors page
    It gets the course based on the course id put in the address bar.
    Then, if the course exists, it renders the tutors.html page and passes
    the list of tutors on that course to the page.
    """
    try:
        course = models.Course.objects.get(pk=course_id)
    except models.Course.DoesNotExist:
        raise Http404("Course does not exist")
    # student_set has the info of all of the users who are marked as tutors
    # for this course
    return render(
        request,
        'tutor/tutors.html',
        {"tutors": course.student_set.all()})


def startstop(request):
    return render(request, 'tutor/startstop.html')


@login_required(login_url='/admin/login/')
def add_users(request):
    """
    This will use the google api to scrape the user's contact list
    for people with reed emails, then add those people to the db
    with their profile ids.
    """
    # Make sure the user has the permissions to change the db
    if not (request.user.has_perm('auth.add_user') or
            request.user.has_perm('auth.change_user') or
            request.user.has_perm('tutor.add_student') or
            request.user.has_perm('tutor.change_student')):
        return render(request, "error/403.html", status=403)

    # This block makes sure we have the credentials and they're
    # not expired
    credentials = request.session.get("credentials")
    if credentials is None:
        return redirect('oauth2callback')
    credentials = client.OAuth2Credentials.from_json(credentials)
    if credentials.access_token_expired:
        return redirect('oauth2callback')

    # Now we get the contacts from the user
    http = credentials.authorize(httplib2.Http())
    service = discovery.build(
        'people',
        'v1',
        http=http,
        discoveryServiceUrl='https://people.googleapis.com/$discovery/rest')
    results = service.people().connections().list(
        resourceName='people/me',
        pageSize=2000,
        requestMask_includeField="person.names,person.email_addresses,person.metadata",
    ).execute()
    connections = results.get('connections', [])

    # Now we add the connections to the db as users
    reedmail = re.compile('.*@reed\.edu$')  # regex that matches reed emails

    # print out every reed email in the connections list
    # and its related profile id
    for con in connections:

        emails = con.get("emailAddresses", [])
        reed_addr = None
        # get reed email
        for email in emails:
            addr = email.get("value", "")
            if addr and reedmail.match(addr):
                reed_addr = addr
        # get profileid
        sources = con.get("metadata", {}).get("sources", [])
        profile_id = None
        for source in sources:
            if source.get("type") == "PROFILE":
                profile_id = source.get("id")
        # get first and last name
        # this gets the first thing in the "names" list
        first_name = con.get("names", [{}])[0].get("givenName")
        last_name = con.get("names", [{}])[0].get("familyName")

        if reed_addr and profile_id and first_name and last_name:
            # @reed.edu is 9 characters
            username = reed_addr[0:-9]
            pw = str(urlsafe_b64encode(os.urandom(6)))[2:10]

            # see if this user already exists
            usr = User.objects.filter(email=reed_addr).first()
            # I'm using .filter and then .first rather than .get
            # because .get throws an error if the user does not
            # exist while .first just returns None
            if usr:
                stu = models.Student.objects.get(user=usr)
            else:
                usr = User.objects.create_user(
                    username,
                    first_name=first_name,
                    last_name=last_name,
                    email=reed_addr,
                    password=pw)
                stu = models.Student.objects.create(user=usr)
            stu.profile_id = profile_id
            usr.save()
            stu.save()

    return HttpResponse("Users were added!")


def oauth2callback(request):
    """
    callback for google api stuff
    """
    print(request.GET)
    flow = client.flow_from_clientsecrets(
        'client_secrets.json',
        scope='https://www.googleapis.com/auth/contacts.readonly',
        redirect_uri=request.build_absolute_uri(reverse('oauth2callback')))
    if 'code' not in request.GET:
        auth_uri = flow.step1_get_authorize_url()
        return redirect(auth_uri)
    else:
        auth_code = request.GET.get('code')
        credentials = flow.step2_exchange(auth_code)
        request.session['credentials'] = credentials.to_json()
        return redirect('add_users')

tutor/templates/tutor/about.html
<!-- This template is for our About Us page. It displays our names and majors as well as links to the
Software Design program we worked for.  -->
{% extends "tutor/base.html" %}
{% load static %}
{% block title %}
About Us
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}" />
{% endblock %}

{% block content %}
<h1 class="about_us">About Us!</h1>
<div class="about_text">
    <p>
        This web application was created by four Reed students as part of the <a href="http://www.reed.edu/sds/">Reed College
    Software Design Studio</a>. We worked tirelessly during Summer 2017 to bring this spectactular
    content to you. The Internet is really complicated, okay. Check out our code <a href="https://github.com/reed-college/paneity">here</a>.</p>
<div id="names">
    <ul>
        <li>Miriam Bern '19 Alternative Biology</li>
        <li>Alex Grant '18 Mathematics/Computer Science</li>
        <li>Marika Swanberg '19 Mathematics</li>
        <li>Corbin Buff '19 English</li>
    </ul>
</div>

</div>
<img src="https://www.colourbox.com/preview/1053640-4-business-people-celebrating-an-achieved-aim.jpg"></img>
{% endblock %}

tutor/templates/tutor/base.html
<!-- This page contains our banner, navigation bar, Reed College logo and text, and a login/logout button. -->
<!doctype html>
<html>
<head>
{% load static %}
<link rel="icon" href="{% static 'images/REEDGRIFFIN.png' %}">
<title>
Paneity | {% block title %}{% endblock %}
</title>


{% block bootstrap %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- Google fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato|Nunito|Crimson+Text"/>
{% endblock %}

{# main stylsheet #}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
{# stuff to make mobile friendly #}
<meta name="viewport" content="width=device-width, initial-scale=1">

{% block head %}

{% endblock %}
</head>
<body>
    {% include 'spirit/_banner.html' %}
    <div class="row">
        <div class="col-xs-12">
            <div class="username_login">
                {% if user.username %}
                <p>You are currently logged in as: {{user.username}}</p>
                {% else %}
                <p>You are not logged in.</p>
                {% endif %}
                <div class="about">
                    <a href="{% url "tutor:about" %}">About Us</a>
                </div>
                <!-- This button says 'login' if the user isn't logged in and it displays "logout" if the user is logged in. -->
                <h6 class="login_logout">{% if user.username %}<a class="myButton" href= "{{ LOGOUT_URL }}">LOG OUT</a>{% else %}<a class="myButton" href="{{LOGIN_URL}}">LOG IN</a>{% endif%}</h6>

            </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}

    {% block extra_js %}{% endblock %}

</body>
</html>

tutor/templates/tutor/inbox.html
<!-- This template dictates the page where users who are logged in will see their message inbox -->
{% extends "tutor/base.html" %}
{% load static %}
{% load i18n %}
{% load tutor_extras %}

{% block title%}
    Inbox
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/inbox.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="title">Message Inbox</h2>
        <h3 class="helptext">Select a conversation below:</h3>
        <div class="messages-div">
            <table class="messages-table table table-hover">
                <tbody id="new-message-div">

                </tbody>
                <tbody id="old-message-div">
                    {% for dialog in dialogs %}
                        {# this part figures out if the current user is the opponent, #}
                        {# or the owner of the dialog #}
                        {% with username=dialog|other_username:request.user.username %}
                            <tr id="{{username}}-element" class="clickable-row" data-href='{% url "dialogs_detail" username %}'>
                                <td class="name-cell"><b>{{username|get_name}}</b></td>
                                <td class="message-cell">
                                    {% with dialog|most_recent_message:request.user.username as message %}
                                        {{ message.text }}
                                    {% endwith %}
                                </td>
                            </tr>
                            {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <table class="hidden">
        <tbody id="no-messages-template">
            <tr id="no-messages-element" class="danger">
                <td>No Messages</td>
            </tr>
        </tbody>
    </table>
    <table class="hidden">
        <tbody id="new-message-template">
                {# this assumes that the url for dialog_detail will be the same as dialogs, but with a username on the end #}
            <tr id="[username]-element" class="clickable-row success" data-href="{% url "dialogs" %}[username]">
                <td class="name-cell"><b>[name]</b></td>
                <td class="message-cell">
                    [message]
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

{% block extra_js %}
    <script>
        var baseWsServerPath = "{{ ws_server_path }}";
        var sessionKey = '{{ request.session.session_key }}'
    </script>
    <script src="{% static 'js/inbox.js' %}"></script>
{% endblock %}

tutor/templates/tutor/index.html
<!-- This code is for the homepage. It lists all of the courses and has a search bar to easily find courses. -->
{% extends "tutor/base.html" %}
{% load static %}
{% block title %}
Homepage
{% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="homepage">
        <!-- the header below checks if the user logged in has a first name, a username, or if they aren't logged in, and it then
        displays the appropriate greeting. It's all in one line because the formatting on the page got weird otherwise. -->
        <h2>Welcome{% if user.first_name %}, {{user.first_name}}{% elif user.username %}, {{user.username}}{% endif %}!</h2>
        <h3> To find a tutor, please select a course from the list below: </h3>
        <div class="courselisting">
            <input type="text" id="myInput" class="input" onkeyup="myFunctionExport()" placeholder="Search for courses..." title="Type in a course or subject name">
            <ul id="myUL" class="myUL">
                {% if request.user.student.enrolled_classes.all %}
                    <li><a href="#" class="header">Enrolled Courses</a></li>
                    {% for course in request.user.student.enrolled_classes.all %}
                        <li><a href = "{{course.id}}/tutors" class="subheader">{{course}} {{course.title}}</a></li>
                    {% endfor %}
                {% endif %}

                {% for subject in Subjects %}
                    <li><a href="#" class="header">{{subject}}</a></li>
                    {% for classes in subject.course_set.all %}
                        <li><a href = "{{classes.id}}/tutors" class="subheader">{{classes}} {{classes.title}}</a></li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<script src="{% static 'js/index.js' %}"></script>


{% endblock %}

tutor/templates/tutor/tutorchat.html
{% extends "tutor/base.html" %}
{% load static %}
{% load i18n %}
{% load tutor_extras %}

{% block title%}
    Inbox
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/tutorchat.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="title">Message Inbox</h2>
        <h3 class="helptext">Select a conversation below:</h3>
        <div class="messages-div">
            <table class="messages-table table table-hover">
                <tbody id="new-message-div">

                </tbody>
                <tbody id="old-message-div">
                    {% for dialog in dialogs %}
                        {# this part figures out if the current user is the opponent, #}
                        {# or the owner of the dialog #}
                        {% with username=dialog|other_username:request.user.username %}
                            <tr id="{{username}}-element" class="clickable-row" data-href='{% url "dialogs_detail" username %}'>
                                <td class="name-cell"><b>{{username|get_name}}</b></td>
                                <td class="message-cell">
                                    {% with dialog|most_recent_message:request.user.username as message %}
                                        {{ message.text }}
                                    {% endwith %}
                                </td>
                            </tr>
                            {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <table class="hidden">
        <tbody id="no-messages-template">
            <tr id="no-messages-element" class="danger">
                <td>No Messages</td>
            </tr>
        </tbody>
    </table>
    <table class="hidden">
        <tbody id="new-message-template">
                {# this assumes that the url for dialog_detail will be the same as dialogs, but with a username on the end #}
            <tr id="[username]-element" class="clickable-row success" data-href="{% url "dialogs" %}[username]">
                <td class="name-cell"><b>[username]</b></td>
                <td class="message-cell">
                    [message]
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

{% block extra_js %}
    <script>
        var base_ws_server_path = "{{ ws_server_path }}";
        var session_key = '{{ request.session.session_key }}'
    </script>
    <script src="{% static 'js/tutorchat.js' %}"></script>
{% endblock %}

tutor/templates/tutor/tutors.html
<!-- This template displays the office hours, tutoring hours, and tutors for a given course. -->
{% extends "tutor/base.html" %}
{% block title %}
{{course_name}} Tutors
{% endblock %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/tutors.css' %}" />
{% endblock %}

{% block content %}
    {% load tutor_extras %}
    <div class="row">
        <div class="col-xs-12">
            <h3 class="tutortitle"> {{course_name}} Tutoring</h3>
            <div class="hours">
                <h4 id="office_hours">Office Hours:</h4>
                    <p id="office/dropin">{{course_name.office_hours|linebreaksbr}}</p>
                <h4 id="dropin_hours">Drop-in Tutoring Hours:</h4>
                    <p id = "office_dropin">{{course_name.drop_in_hrs|linebreaksbr}}</p>
            </div>

            <div class="tutorsdiv">
            {# prints the first and last name of each tutor #}
                <table class="table">
                    <tr>
                        <th>Tutors:</th>
                    </tr>
                {% for tutor in tutors %}
                    <tr>
                        <td class="on-off-cell">
                            <div id="user-{{tutor.user.username}}" class="offline"></div> 
                        </td>
                    {% if tutor.user.first_name or tutor.user.last_name %}
                        <td>
                            {{tutor.user.first_name}}
                            {{tutor.user.last_name}}
                        </td>
                    {% else %}
                        <td>
                            {{tutor.user.username}}
                        </td>
                    {% endif %}

                        <td>
                            <a class="tutorlink" href="{% url 'dialogs_detail' tutor.user.username %}">Get help from {{tutor.user.first_name}}!</a>
                        </td>
                        <td>
                            <a class="tutorlink" href="mailto:{{tutor.user.email}}">{{tutor.user.email}}</a>
                        </td>
                        <td class="last-log">
                            <small>
                                Last Login:
                                {% if not tutor.user.last_login %}
                                    Never

                                {% comment %}
                                This checks if a tutor has logged in in the
                                last day.
                                It uses a function in
                                tutor/templatetags/tutor_extras.py
                                {% endcomment %}
                                {% elif tutor.user.last_login|add:day|datetime_ge:dnow %}
                                    {{tutor.user.last_login|timesince}} ago

                                {% comment %}
                                Similar to the last clause, this one checks
                                if they have logged in within the last week
                                {% endcomment %}
                                {% elif tutor.user.last_login|add:week|datetime_ge:dnow %}
                                    {{tutor.user.last_login|date:"l"}}
                                {% else %}
                                    {{tutor.user.last_login|date:"m/d/y"}}
                                {% endif %}
                            </small>
                        </td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        var baseWsServerPath = "{{ ws_server_path }}";
        var sessionKey = '{{ request.session.session_key }}';
        var usersCheckList = [
          {% for tutor in tutors %}
              "{{ tutor.user.username }}",
          {% endfor %}
        ];
    </script>
    <script src="{% static 'js/tutors.js' %}"></script>
{% endblock %}